services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"

volumes:
  mongo-data:
