name: Deploy Docker Images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/digiballot-frontend:latest ./Frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/digiballot-frontend:latest

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/digiballot-backend:latest ./Backend
          docker push ${{ secrets.DOCKER_USERNAME }}/digiballot-backend:latest

      - name: Trigger Render Deploy (Frontend)
        run: |
          curl -X POST ${{ secrets.RENDER_HOOK_FRONTEND }}

      - name: Trigger Render Deploy (Backend)
        run: |
          curl -X POST ${{ secrets.RENDER_HOOK_BACKEND }}
